"""check_design_system.py: what a local design-system directory lacks before upload.

A minimal directory that meets every requirement exits 0; each requirement removed
in turn is named on its own line and exits 1.
"""

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[2] / "skills" / "design-pages" / "scripts" / "check_design_system.py"

README = """# Board design system

## Sources
Code under page/.

## CONTENT FUNDAMENTALS
Short.

## VISUAL FOUNDATIONS
Ink on paper.

## ICONOGRAPHY
Lucide.

## Index
Everything.

## Intentional additions
None.
"""


def card(group, name):
    return f'<!-- @dsCard group="{group}" viewport="700x150" name="{name}" subtitle="x" -->\n<html></html>\n'


def build(root: Path) -> None:
    (root / "tokens").mkdir()
    (root / "fonts").mkdir()
    (root / "fonts" / "a.woff2").write_bytes(b"x")
    (root / "styles.css").write_text('/* entry */\n@import "tokens/colors.css";\n@import "tokens/fonts.css";\n')
    (root / "tokens" / "colors.css").write_text(":root { --ink: #222; }\n")
    (root / "tokens" / "fonts.css").write_text("@font-face { font-family: A; src: url(../fonts/a.woff2); }\n")
    (root / "readme.md").write_text(README)
    (root / "SKILL.md").write_text("---\nname: board-design\ndescription: Use it.\n---\nRead readme.md.\n")
    (root / "guidelines").mkdir()
    for i in range(12):
        (root / "guidelines" / f"c{i}.html").write_text(card("Colors", f"c{i}"))
    comp = root / "components" / "status"
    comp.mkdir(parents=True)
    (comp / "Lamp.jsx").write_text('import React from "react";\nexport function Lamp(p) { return <span/>; }\n')
    (comp / "Lamp.d.ts").write_text('export interface LampProps { "data-ui"?: string }\n')
    (comp / "Lamp.prompt.md").write_text("The lamp.\n")
    (comp / "status.card.html").write_text(card("Components", "Status"))
    kit = root / "ui_kits" / "board"
    kit.mkdir(parents=True)
    (kit / "index.html").write_text(card("Board", "Board"))
    (kit / "TopBar.html").write_text('<!-- @startingPoint section="Board" subtitle="x" viewport="1440x52" -->\n')


def run(root):
    return subprocess.run([sys.executable, str(SCRIPT), str(root)], capture_output=True, text=True)


class CheckDesignSystem(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        build(self.root)

    def tearDown(self):
        self.tmp.cleanup()

    def test_complete_directory_passes(self):
        result = run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn("design system complete: 1 components, 12 foundation cards, 1 starting points", result.stdout)

    def assertMiss(self, text):
        result = run(self.root)
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn(text, result.stdout)

    def test_rule_in_styles_css(self):
        (self.root / "styles.css").write_text('@import "tokens/colors.css";\n.x { color: red; }\n')
        self.assertMiss("styles.css:2: not an @import line")

    def test_unresolved_import(self):
        (self.root / "styles.css").write_text('@import "tokens/missing.css";\n')
        self.assertMiss("@import tokens/missing.css does not resolve")

    def test_missing_font_file(self):
        (self.root / "fonts" / "a.woff2").unlink()
        self.assertMiss("font file ../fonts/a.woff2 does not resolve")

    def test_readme_heading(self):
        (self.root / "readme.md").write_text(README.replace("## ICONOGRAPHY", "## Icons"))
        self.assertMiss("readme.md: no `## ICONOGRAPHY` heading")

    def test_too_few_foundation_cards(self):
        (self.root / "guidelines" / "c0.html").unlink()
        self.assertMiss("foundation cards: 11, want at least 12")

    def test_component_without_types(self):
        (self.root / "components" / "status" / "Lamp.d.ts").unlink()
        self.assertMiss("components/status/Lamp.jsx: no sibling Lamp.d.ts")

    def test_component_without_data_ui(self):
        (self.root / "components" / "status" / "Lamp.d.ts").write_text("export interface LampProps {}\n")
        self.assertMiss('components/status/Lamp.d.ts: props declare no "data-ui"')

    def test_component_directory_without_card(self):
        (self.root / "components" / "status" / "status.card.html").unlink()
        self.assertMiss("components/status: 0 @dsCard files in group Components, want 1")

    def test_ui_kit_without_starting_point_is_complete(self):
        (self.root / "ui_kits" / "board" / "TopBar.html").unlink()
        result = run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn("0 starting points", result.stdout)

    def test_generated_file_written_by_hand(self):
        (self.root / "_ds_manifest.json").write_text("{}")
        self.assertMiss("_ds_manifest.json: generated by Claude Design")

    def test_not_a_directory(self):
        result = subprocess.run([sys.executable, str(SCRIPT), str(self.root / "nope")], capture_output=True, text=True)
        self.assertEqual(result.returncode, 2)


if __name__ == "__main__":
    unittest.main()
