#!/usr/bin/env python3
"""把 _fragments/ 里的厂商原生提示词片段按角色渲染进 agents-roster/*.md。

用法:
  python3 scripts/render_agent_prompts.py          # 渲染(幂等,重跑安全)
  python3 scripts/render_agent_prompts.py --check  # 只校验:渲染结果与现文件一致则 0,否则 1

纪律:片段一律逐字拼装,禁止在本脚本里改写片段内容;要换内容改 _fragments/ 并更新 MANIFEST.md。
Claude 系角色(reviewer-*-b)不渲染——它们经 claude-provider preset 已有 Claude Code 原生提示词打底。
"""

import sys
from pathlib import Path

ROSTER = Path(__file__).resolve().parent.parent / "agents-roster"
FRAG = ROSTER / "_fragments"

BEGIN = "<!-- mmw:fragments BEGIN generated by scripts/render_agent_prompts.py; edit _fragments/, not this block -->"
END = "<!-- mmw:fragments END -->"

# 角色 → 有序片段清单(文件名, 前置标题;标题为空表示直接衔接上一段)
BRIDGE_RW = [("pi-subagents-tool-bridge.md", None)]
BRIDGE_RO = [("pi-subagents-tool-bridge-readonly.md", None)]
AUTONOMY = [("codex56-autonomy-persistence.md", None)]
ACT_REPORT = [
    ("cc-act-when-ready.md", "## Act and report"),
    ("cc-action-safety-truthful-reporting.md", ""),
]
CODE_DOCTRINE = [
    ("codex52-root-cause.md", "## Code changes"),
    ("cc-no-compatibility-hacks.md", ""),
    ("cc-no-unnecessary-additions.md", ""),
    ("cc-no-unnecessary-error-handling.md", ""),
    ("cc-comment-why-only.md", ""),
    ("cc-comment-no-what-no-task-context.md", ""),
    ("codex56-worktree-safety.md", ""),
]
THOROUGHNESS = [("cursor-context-thoroughness.md", "## Context gathering")]

ROLES = {
    "pack-executor.md": BRIDGE_RW + AUTONOMY + ACT_REPORT + CODE_DOCTRINE,
    "pack-executor-capable.md": BRIDGE_RW + AUTONOMY + ACT_REPORT + CODE_DOCTRINE,
    "plan-writer.md": BRIDGE_RW + AUTONOMY + ACT_REPORT + THOROUGHNESS,
    "code-explorer.md": BRIDGE_RO + AUTONOMY + ACT_REPORT,
    "investigate-topic.md": BRIDGE_RO + AUTONOMY + ACT_REPORT,
    "reviewer-design-a.md": BRIDGE_RO + AUTONOMY + ACT_REPORT,
    "reviewer-plan-a.md": BRIDGE_RO + AUTONOMY + ACT_REPORT,
    "reviewer-final-a.md": BRIDGE_RO + AUTONOMY + ACT_REPORT,
    "investigate-synthesizer.md": ACT_REPORT,
}


def build_block(spec: list[tuple[str, str | None]]) -> str:
    parts = [BEGIN]
    for fname, heading in spec:
        text = (FRAG / fname).read_text().strip()
        if heading:
            parts.append(heading + "\n\n" + text)
        else:
            parts.append(text)
    parts.append(END)
    return "\n\n".join(parts)


def render(path: Path, block: str) -> str:
    src = path.read_text()
    if BEGIN in src:
        head, rest = src.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail
    # 首次插入:frontmatter 结束后
    fm_end = src.index("---", src.index("---") + 3) + 3
    return src[:fm_end] + "\n\n" + block + src[fm_end:]


def main() -> int:
    check = "--check" in sys.argv
    dirty = []
    for fname, spec in ROLES.items():
        path = ROSTER / fname
        rendered = render(path, build_block(spec))
        if path.read_text() != rendered:
            if check:
                dirty.append(fname)
            else:
                path.write_text(rendered)
                print(f"rendered {fname}")
    if check:
        if dirty:
            print("stale:", ", ".join(dirty))
            return 1
        print("all roster files up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
