#!/usr/bin/env python3
"""物化、安装、检查或卸载 MMW 的 Codex 原生 subagent。"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import NoReturn

from config import CodexConfigError, load_profiles as load_codex_profiles

CODEX_ROOT = Path(__file__).resolve().parent
MMW_ROOT = CODEX_ROOT.parent
AGENTS_DIR = CODEX_ROOT / "agents"
BODY_DIR = MMW_ROOT / "agent-src" / "bodies"
PLUGIN_ROOT = MMW_ROOT
MANAGED_HEADER = "# Generated by MMW Codex runtime. Do not edit."
MARKETPLACE_NAME = "mmw-codex"
PLUGIN_NAME = "mmw"


def die(message: str, code: int = 1) -> NoReturn:
    print(f"mmw codex runtime: {message}", file=sys.stderr)
    raise SystemExit(code)


def load_profiles() -> dict:
    try:
        return load_codex_profiles()
    except CodexConfigError as exc:
        die(str(exc))


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_agent(role: str, profile: dict) -> str:
    body_path = BODY_DIR / profile["body"]
    if not body_path.is_file():
        die(f"{role} 的 body 不存在: {body_path}")
    body = body_path.read_text(encoding="utf-8").strip()
    method = profile.get("method_skill")
    if method:
        body = (
            f"开始前必须完整读取并遵守 `${method}`。方法论只保留在该技能中。\n\n"
            + body
        )
    if '"""' in body:
        die(f"{role} 的 body 含 TOML 三引号，无法安全物化")
    fields = [
        MANAGED_HEADER,
        f"name = {toml_string(profile['name'])}",
        f"description = {toml_string(profile['description'])}",
        f"model = {toml_string(profile['model'])}",
        f"model_reasoning_effort = {toml_string(profile['thinking'])}",
        f"sandbox_mode = {toml_string(profile.get('sandbox_mode', 'read-only'))}",
        'developer_instructions = """',
        body,
        '"""',
        "",
    ]
    return "\n".join(fields)


def rendered_agents() -> dict[str, str]:
    profiles = load_profiles()
    agents = profiles.get("subagents") or {}
    expected_roles = {"investigator", "reviewer-gpt", "planner", "designer"}
    if set(agents) != expected_roles:
        die(f"Codex 原生 subagent 必须是 {', '.join(sorted(expected_roles))}")
    rendered: dict[str, str] = {}
    for role, profile in agents.items():
        model = str(profile.get("model") or "")
        if not model.startswith("gpt-"):
            die(f"{role} 必须使用 Codex 内置 GPT 模型")
        name = str(profile.get("name") or "")
        if not name:
            die(f"{role} 缺 name")
        rendered[f"{name}.toml"] = render_agent(role, profile)
    return rendered


def write_atomic(path: Path, content: str, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, raw_tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    tmp = Path(raw_tmp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if mode is not None:
            os.chmod(tmp, mode)
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def bundled_files() -> dict[Path, str]:
    files: dict[Path, str] = {}
    try:
        source_mcp = json.loads((MMW_ROOT / ".mcp.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        die(f"读不到 MMW MCP 定义: {exc}")
    servers = source_mcp.get("mcpServers")
    if not isinstance(servers, dict):
        die("MMW .mcp.json 缺 mcpServers")

    codex_servers = {}
    for name, spec in servers.items():
        if not isinstance(spec, dict) or not isinstance(spec.get("command"), str):
            die(f"Codex plugin 只支持由 mmw mcp serve 启动的 stdio 服务器: {name}")
        codex_servers[name] = {
            "command": "mmw",
            "args": ["mcp", "serve", name],
        }

    files[Path(".mcp-codex.json")] = (
        json.dumps(codex_servers, ensure_ascii=False, indent=2) + "\n"
    )
    return files


def materialize_plugin(check: bool) -> int:
    failures = 0
    for rel, content in bundled_files().items():
        target = PLUGIN_ROOT / rel
        if check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                print(f"异  {target}", file=sys.stderr)
                failures += 1
        else:
            write_atomic(target, content)
            print(f"写  {target}")

    command = [
        sys.executable,
        str(MMW_ROOT / "cli" / "lib" / "materialize_skills.py"),
        "--host",
        "codex",
    ]
    if check:
        command.append("--check")
    proc = subprocess.run(command, check=False)
    if proc.returncode != 0:
        failures += 1
    return 1 if failures else 0


def materialize(check: bool) -> int:
    expected = rendered_agents()
    existing = {
        path.name: path.read_text(encoding="utf-8")
        for path in AGENTS_DIR.glob("mmw-*.toml")
        if path.is_file()
    }
    if check:
        failures = 0
        for name, content in expected.items():
            if existing.get(name) != content:
                print(f"异  {AGENTS_DIR / name}", file=sys.stderr)
                failures += 1
        for name in existing.keys() - expected.keys():
            print(f"多  {AGENTS_DIR / name}", file=sys.stderr)
            failures += 1
        failures += materialize_plugin(check=True)
        return 1 if failures else 0
    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    for name in existing.keys() - expected.keys():
        (AGENTS_DIR / name).unlink()
    for name, content in expected.items():
        write_atomic(AGENTS_DIR / name, content)
        print(f"写  {AGENTS_DIR / name}")
    return materialize_plugin(check=False)


def plugin_version(root: Path) -> str | None:
    manifest = root / ".codex-plugin" / "plugin.json"
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if data.get("name") != PLUGIN_NAME or not isinstance(data.get("version"), str):
        return None
    return data["version"]


def valid_plugin_root(root: Path, version: str) -> bool:
    return (
        plugin_version(root) == version
        and (root / "cli" / "mmw").is_file()
        and (root / "codex" / "runtime.py").is_file()
        and (root / "codex" / "config.py").is_file()
        and (root / "skills-codex" / "mmw-start" / "SKILL.md").is_file()
        and (root / ".mcp-codex.json").is_file()
        and (root / ".mcp.json").is_file()
        and (root / "codex" / "profiles.json").is_file()
        and (root / "mcp" / "resolve.py").is_file()
        and (root / "mcp" / "serve.py").is_file()
    )


def installed_plugin_root() -> Path:
    """定位 App 已安装的完整 plugin；源码 checkout 不能充当运行时。"""
    version = plugin_version(MMW_ROOT)
    if not version:
        die(f"{MMW_ROOT} 不是有效的 MMW Codex plugin")

    override = os.environ.get("MMW_CODEX_PLUGIN_ROOT")
    if override:
        candidate = Path(override).expanduser().resolve()
        if valid_plugin_root(candidate, version):
            return candidate
        die(f"MMW_CODEX_PLUGIN_ROOT 不是版本 {version} 的完整 MMW plugin: {candidate}")

    cache = codex_home() / "plugins" / "cache" / MARKETPLACE_NAME / PLUGIN_NAME
    candidates = [cache / version, cache / "local"]
    for candidate in candidates:
        candidate = candidate.resolve()
        if valid_plugin_root(candidate, version):
            return candidate

    die(
        f"Codex App 尚未安装 MMW plugin {version}；先从 {MARKETPLACE_NAME} 安装或更新，"
        "再运行 runtime.py install"
    )


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex").expanduser()


def install() -> int:
    if materialize(check=True):
        die("仓库内 Codex agent 产物已漂移，先运行 runtime.py materialize")
    plugin_root = installed_plugin_root()
    target_agents = codex_home() / "agents"
    target_agents.mkdir(parents=True, exist_ok=True)
    expected_agents = {source.name for source in AGENTS_DIR.glob("mmw-*.toml")}
    for source in sorted(AGENTS_DIR.glob("mmw-*.toml")):
        target = target_agents / source.name
        if target.exists() and not target.read_text(encoding="utf-8").startswith(MANAGED_HEADER):
            die(f"拒绝覆盖非 MMW 管理的 agent: {target}")
    for target in sorted(target_agents.glob("mmw-*.toml")):
        if target.name in expected_agents:
            continue
        if target.read_text(encoding="utf-8").startswith(MANAGED_HEADER):
            target.unlink()
            print(f"删  {target}")
    for source in sorted(AGENTS_DIR.glob("mmw-*.toml")):
        target = target_agents / source.name
        write_atomic(target, source.read_text(encoding="utf-8"))
        print(f"装  {target}")
    print(f"Codex plugin 已安装在 {plugin_root}")
    return 0


def check() -> int:
    failures = materialize(check=True)
    plugin_root = installed_plugin_root()
    expected = rendered_agents()
    target_agents = codex_home() / "agents"
    for name, content in expected.items():
        target = target_agents / name
        if not target.is_file() or target.read_text(encoding="utf-8") != content:
            print(f"缺或旧  {target}", file=sys.stderr)
            failures += 1
    expected_names = set(expected)
    for target in sorted(target_agents.glob("mmw-*.toml")):
        if target.name not in expected_names and target.read_text(encoding="utf-8").startswith(MANAGED_HEADER):
            print(f"旧残留  {target}", file=sys.stderr)
            failures += 1
    if failures:
        return 1
    print(f"Codex 原生 subagent 与已安装 plugin 一致：{plugin_root}")
    return 0


def uninstall() -> int:
    for path in sorted((codex_home() / "agents").glob("mmw-*.toml")):
        if path.read_text(encoding="utf-8").startswith(MANAGED_HEADER):
            path.unlink()
            print(f"删  {path}")
    print("Codex plugin 请在 App 的 Plugins 页面卸载；本脚本不直接修改 App plugin 状态。")
    return 0


def check_mcp_configs(paths: list[str]) -> int:
    """拒绝会绕过已安装 plugin 的旧 MCP 命令；等价的显式项目配置允许保留。"""
    expected = {
        name: {"command": "mmw", "args": ["mcp", "serve", name]}
        for name in ("serena", "graphify", "context7")
    }
    failures = 0
    for raw_path in paths:
        path = Path(raw_path).expanduser()
        if not path.is_file():
            continue
        try:
            payload = tomllib.loads(path.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError) as exc:
            print(f"读不到 Codex 配置 {path}: {exc}", file=sys.stderr)
            failures += 1
            continue
        servers = payload.get("mcp_servers") or {}
        if not isinstance(servers, dict):
            print(f"Codex 配置的 mcp_servers 不是表: {path}", file=sys.stderr)
            failures += 1
            continue
        for name, wanted in expected.items():
            actual = servers.get(name)
            if actual is None:
                continue
            if not isinstance(actual, dict) or any(
                actual.get(field) != value for field, value in wanted.items()
            ) or actual.get("enabled") is False or "cwd" in actual:
                print(
                    f"{path}: mcp_servers.{name} 没有通过已安装的 MMW plugin 启动",
                    file=sys.stderr,
                )
                failures += 1
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="管理 MMW Codex 原生运行时")
    parser.add_argument(
        "command",
        choices=("materialize", "install", "check", "uninstall", "check-mcp-config"),
    )
    parser.add_argument("paths", nargs="*")
    parser.add_argument("--check", action="store_true", help="materialize 时只检查漂移")
    args = parser.parse_args(argv)
    if args.command == "materialize":
        return materialize(args.check)
    if args.command == "check-mcp-config":
        if args.check or not args.paths:
            die("check-mcp-config 需要至少一个配置路径", code=2)
        return check_mcp_configs(args.paths)
    if args.paths:
        die(f"{args.command} 不接受路径参数", code=2)
    if args.check:
        die("--check 只用于 materialize", code=2)
    return {"install": install, "check": check, "uninstall": uninstall}[args.command]()


if __name__ == "__main__":
    raise SystemExit(main())
