#!/usr/bin/env python3
"""物化、安装、检查或卸载 MMW 的 Codex 原生 subagent。"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import NoReturn

from config import CodexConfigError, load_profiles as load_codex_profiles

CODEX_ROOT = Path(__file__).resolve().parent
MMW_ROOT = CODEX_ROOT.parent
BODY_DIR = MMW_ROOT / "agent-src" / "bodies"
MANAGED_HEADER = "# Generated by MMW Codex runtime. Do not edit."


def die(message: str, code: int = 1) -> NoReturn:
    print(f"mmw codex runtime: {message}", file=sys.stderr)
    raise SystemExit(code)


def load_profiles() -> dict:
    try:
        return load_codex_profiles()
    except CodexConfigError as exc:
        die(str(exc))


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_agent(role: str, profile: dict) -> str:
    body_path = BODY_DIR / profile["body"]
    if not body_path.is_file():
        die(f"{role} 的 body 不存在: {body_path}")
    body = body_path.read_text(encoding="utf-8").strip()
    method = profile.get("method_skill")
    if method:
        body = (
            f"Call `{method}` first. Method lives only in that skill.\n\n"
            + body
        )
    if '"""' in body:
        die(f"{role} 的 body 含 TOML 三引号，无法安全物化")
    fields = [
        MANAGED_HEADER,
        f"name = {toml_string(profile['name'])}",
        f"description = {toml_string(profile['description'])}",
        f"model = {toml_string(profile['model'])}",
        f"model_reasoning_effort = {toml_string(profile['thinking'])}",
        f"sandbox_mode = {toml_string(profile.get('sandbox_mode', 'read-only'))}",
        'developer_instructions = """',
        body,
        '"""',
        "",
    ]
    return "\n".join(fields)


def rendered_agents() -> dict[str, str]:
    profiles = load_profiles()
    agents = profiles.get("subagents") or {}
    expected_roles = {
        "reviewer-gpt",
        "planner",
        "designer",
    }
    if set(agents) != expected_roles:
        die(f"Codex 原生 subagent 必须是 {', '.join(sorted(expected_roles))}")
    rendered: dict[str, str] = {}
    for role, profile in agents.items():
        model = str(profile.get("model") or "")
        if not model.startswith("gpt-"):
            die(f"{role} 必须使用 Codex 内置 GPT 模型")
        name = str(profile.get("name") or "")
        if not name:
            die(f"{role} 缺 name")
        rendered[f"{name}.toml"] = render_agent(role, profile)
    return rendered


def write_atomic(path: Path, content: str, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, raw_tmp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    tmp = Path(raw_tmp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if mode is not None:
            os.chmod(tmp, mode)
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex").expanduser()


def agents_dir() -> Path:
    return codex_home() / "agents"


def materialize(check: bool) -> int:
    """把角色渲染进 ~/.codex/agents/。

    产物不入库。上一版先渲染进仓库的 mmw/codex/agents/，再由 install() 逐个拷到
    用户目录——中间那一跳没有任何人需要，它只是多出一处会漂的副本和一道防它漂的
    检查。Cursor 与 Grok 一直是直接渲染进用户目录的，这里跟上。

    目录里同名的文件没有 MMW 的管理头就不动它，报错退出：那可能是用户自己写的
    agent，覆盖掉他不会知道。
    """
    expected = rendered_agents()
    target_dir = agents_dir()
    existing = {
        path.name: path.read_text(encoding="utf-8")
        for path in target_dir.glob("mmw-*.toml")
        if path.is_file()
    }
    if check:
        failures = 0
        for name, content in expected.items():
            if existing.get(name) != content:
                print(f"缺或旧  {target_dir / name}", file=sys.stderr)
                failures += 1
        for name, content in existing.items():
            if name not in expected and content.startswith(MANAGED_HEADER):
                print(f"旧残留  {target_dir / name}", file=sys.stderr)
                failures += 1
        return 1 if failures else 0

    for name, content in existing.items():
        if name not in expected and not content.startswith(MANAGED_HEADER):
            die(f"拒绝覆盖非 MMW 管理的 agent: {target_dir / name}")
    for name in expected:
        current = existing.get(name)
        if current is not None and not current.startswith(MANAGED_HEADER):
            die(f"拒绝覆盖非 MMW 管理的 agent: {target_dir / name}")

    target_dir.mkdir(parents=True, exist_ok=True)
    for name, content in existing.items():
        if name not in expected and content.startswith(MANAGED_HEADER):
            (target_dir / name).unlink()
            print(f"删  {target_dir / name}")
    for name, content in expected.items():
        write_atomic(target_dir / name, content)
        print(f"装  {target_dir / name}")
    return 0


def install() -> int:
    return materialize(check=False)


def check() -> int:
    if materialize(check=True):
        return 1
    print("Codex 原生 subagent 与角色真源一致")
    return 0


def uninstall() -> int:
    for path in sorted(agents_dir().glob("mmw-*.toml")):
        if path.read_text(encoding="utf-8").startswith(MANAGED_HEADER):
            path.unlink()
            print(f"删  {path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="管理 MMW Codex 原生运行时")
    parser.add_argument(
        "command",
        choices=("materialize", "install", "check", "uninstall"),
    )
    parser.add_argument("paths", nargs="*")
    parser.add_argument("--check", action="store_true", help="materialize 时只检查漂移")
    args = parser.parse_args(argv)
    if args.command == "materialize":
        return materialize(args.check)
    if args.paths:
        die(f"{args.command} 不接受路径参数", code=2)
    if args.check:
        die("--check 只用于 materialize", code=2)
    return {"install": install, "check": check, "uninstall": uninstall}[args.command]()


if __name__ == "__main__":
    raise SystemExit(main())
